version: '3.8'

services:
  todo-nest:
    container_name: todo-nest
    image: snippymr/todo-nest:latest
    build:
      context: .
    environment:
      PORT: 7000
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: todo
      POSTGRES_PASSWORD: root
      POSTGRES_PORT: 5432
      JWT_SECRET: flex
      JWT_EXPIRES_IN: 150d
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 7000:7000
      - 9229:9229
    command: npm run start:dev
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
  postgres:
    image: postgres:12
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
    container_name: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: todo
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
