version: '3.8'

services:
  app:
    build: .
    container_name: todo-nest
    image: snippymr/todo-nest:latest
    restart: always
    ports:
      - 7000:7000
    environment:
      PORT: 7000
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: todo
      POSTGRES_PASSWORD: root
      POSTGRES_PORT: 5432
      JWT_SECRET: flex
      JWT_EXPIRES_IN: 150d
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: todo
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
